### ISSUE TITLE
tag_gmm and sed_gmm examples

### ISSUE THREAD

**Issue by TKeutgens** [DCASE-REPO/dcase_util#25]
#### Description
When trying to execute the tag_gmm and sed_gmm examples an AttributeError: 'dict' object has no attribute 'lower' occurs. 

#### Steps/Code to Reproduce
tag_gmm and sed_gmm examples

#### Actual Results
The console output is: . 
[I] Learning
[I] ========================================
[I]     Fold 1
[E] Uncaught exception 	(logging.py:221)
File ".....\dcase_util\utils\files.py", line 758, in detect_based_on_filename
    extension = os.path.splitext(filename.lower())[1]
AttributeError: 'dict' object has no attribute 'lower'

#### Versions

Windows-10-10.0.14393-SP0
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.1
SciPy 1.3.1
Matplotlib 3.1.1
librosa 0.7.0

**Comment by toni-heittola** [comment]
Thanks for reporting these issues. 

Issues are now fixed with commits 322b5a50610803ede3d1cfd039bb7d8eede4d0b8, 63bbb5f2db11f957c67600b70f1e7b7c52536d56 and 614b77256b8a954ed3f5e5388300c361d957d899 in the develop branch. These commits will be included in the upcoming version 0.2.11. The new version should be released within one week.
