### ISSUE TITLE
Urllib.error.URLError when dowdloading dcase2013_scene_classification dataset

### ISSUE THREAD

**Issue by cjf1699** [DCASE-REPO/dcase_util#30]
I got an issue

> urllib.error.URLError: urlopen error timed out

 when I try to execute:
`python  asc_gmm_simple.py`

However, my network connection is fine when visiting other websites. I think perhaps the reason is the network connection is weak ? Is there a mirror source of the dataset? Or is it for other reasons? Thanks for help!

**Comment by toni-heittola** [comment]
Most likely this is due to poor quality of your network connection. I just tested the dataset download code, and it works at least in my setup. 

For now, you can manually try to download the dataset and possibly use some download manager to be able to continue the broken download.

Download link to the dataset is https://archive.org/download/dcase2013_scene_classification/scenes_stereo.zip (https://github.com/DCASE-REPO/dcase_util/blob/master/dcase_util/datasets/dcase2013.py#L66), and you should place the package under dcase_util/examples/datasets/DCASE2013-acoustic-scenes-development/ 

After that, you can run 'asc_gmm_simple.py' code, and it will extract the package and move forward.

**Comment by cjf1699** [comment]
> Most likely this is due to poor quality of your network connection. I just tested the dataset download code, and it works at least in my setup.
> 
> For now, you can manually try to download the dataset and possibly use some download manager to be able to continue the broken download.
> 
> Download link to the dataset is https://archive.org/download/dcase2013_scene_classification/scenes_stereo.zip (https://github.com/DCASE-REPO/dcase_util/blob/master/dcase_util/datasets/dcase2013.py#L66), and you should place the package under dcase_util/examples/datasets/DCASE2013-acoustic-scenes-development/
> 
> After that, you can run 'asc_gmm_simple.py' code, and it will extract the package and move forward.

Thank you so much!
